version: "3.9"
services:
  auth:
    container_name: auth
    restart: always
    build: /Users/sandeepkumar/code/work/application/gluestack/examples/todoapp-tailwind/backend/services/auth
    volumes:
      - /Users/sandeepkumar/code/work/application/gluestack/examples/todoapp-tailwind/backend/services/auth:/server
      - /server/node_modules
    env_file:
      - /Users/sandeepkumar/code/work/application/gluestack/examples/todoapp-tailwind/backend/services/auth/.env
  engine:
    container_name: engine
    restart: always
    build: /Users/sandeepkumar/code/work/application/gluestack/examples/todoapp-tailwind/backend/engine
    volumes:
      - /Users/sandeepkumar/code/work/application/gluestack/examples/todoapp-tailwind/backend/engine:/server
      - /server/node_modules
    env_file:
      - /Users/sandeepkumar/code/work/application/gluestack/examples/todoapp-tailwind/backend/engine/.env
  nginx:
    container_name: nginx
    restart: always
    build: /Users/sandeepkumar/code/work/application/gluestack/examples/todoapp-tailwind/backend/engine/router
    ports:
      - 9090:80
    volumes:
      - /Users/sandeepkumar/code/work/application/gluestack/examples/todoapp-tailwind/backend/engine/router/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      graphql:
        condition: service_healthy
  graphql:
    container_name: graphql
    restart: always
    image: hasura/graphql-engine:v2.16.1
    ports:
      - 8080:8080
    volumes:
      - /Users/sandeepkumar/code/work/application/gluestack/examples/todoapp-tailwind/backend/services/graphql:/hasura
    env_file:
      - /Users/sandeepkumar/code/work/application/gluestack/examples/todoapp-tailwind/backend/services/graphql/.env
    healthcheck:
      test:
        - CMD-SHELL
        - timeout 1s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1
      interval: 5s
      timeout: 2s
      retries: 20
    depends_on:
      postgres:
        condition: service_healthy
  authservice:
    container_name: authservice
    restart: always
    build: /Users/sandeepkumar/code/work/application/gluestack/examples/todoapp-tailwind/backend/services/auth-service
    volumes:
      - /Users/sandeepkumar/code/work/application/gluestack/examples/todoapp-tailwind/backend/services/auth-service:/server
      - /server/node_modules
    env_file:
      - /Users/sandeepkumar/code/work/application/gluestack/examples/todoapp-tailwind/backend/services/auth-service/.env
  storage:
    container_name: storage
    restart: always
    build: /Users/sandeepkumar/code/work/application/gluestack/examples/todoapp-tailwind/backend/services/storage
    volumes:
      - /Users/sandeepkumar/code/work/application/gluestack/examples/todoapp-tailwind/backend/services/storage:/server
      - /server/node_modules
    env_file:
      - /Users/sandeepkumar/code/work/application/gluestack/examples/todoapp-tailwind/backend/services/storage/.env
  email:
    container_name: email
    restart: always
    build: /Users/sandeepkumar/code/work/application/gluestack/examples/todoapp-tailwind/backend/services/email
    volumes:
      - /Users/sandeepkumar/code/work/application/gluestack/examples/todoapp-tailwind/backend/services/email:/server
      - /server/node_modules
    env_file:
      - /Users/sandeepkumar/code/work/application/gluestack/examples/todoapp-tailwind/backend/services/email/.env
  postgres:
    container_name: postgres
    restart: always
    image: postgres:12
    ports:
      - 5433:5432
    volumes:
      - /Users/sandeepkumar/code/work/application/gluestack/examples/todoapp-tailwind/backend/databases/postgres/db:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    healthcheck:
      test:
        - CMD-SHELL
        - psql -U postgres -d todo_db
      interval: 10s
      timeout: 10s
      retries: 50
      start_period: 30s
